#Create pet
POST http://localhost:8000/pets
Content-Type: application/json

{"name": "gatito",
"year" : 2021,
"kind" : "Cat",
"user_id":1
}

###
#create user alive
POST http://localhost:8000/users/
Content-Type: application/json

{"name": "ironman",
"year" : 1980,
"status" : true
}

###
#create user die
POST http://localhost:8000/users/
Content-Type: application/json

{"name": "hulk",
"year" : 1970,
"status" : false
}

###
#look all pets
GET http://localhost:8000/pets/
Content-Type: application/json

###
#look all users
GET http://localhost:8050/users/
Content-Type: application/json

###
#look one user
GET http://localhost:8000/users/1
Accept: application/json





